/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package factura;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author Diego Mendez
 */
public class MenuAdmin extends javax.swing.JFrame {

    /**
     * Creates new form MenuCliente
     */
    public MenuAdmin() {
        initComponents();
         //cambia el icono de la aplicacion
        this.setIconImage(new ImageIcon(getClass().getResource("../img/logo.png")).getImage());
        //coloca la aplicacion al entro
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCliente1 = new javax.swing.JButton();
        btnCliente2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnCliente3 = new javax.swing.JButton();
        btnCliente4 = new javax.swing.JButton();

        btnCliente1.setBackground(new java.awt.Color(255, 255, 255));
        btnCliente1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Nuevo Cliente.png"))); // NOI18N
        btnCliente1.setToolTipText("Buscar por cliente");
        btnCliente1.setBorder(null);
        btnCliente1.setBorderPainted(false);
        btnCliente1.setContentAreaFilled(false);
        btnCliente1.setFocusable(false);
        btnCliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCliente1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnCliente2.setBackground(new java.awt.Color(255, 255, 255));
        btnCliente2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Nuevo usuario.png"))); // NOI18N
        btnCliente2.setToolTipText("Nuevo usuario");
        btnCliente2.setBorder(null);
        btnCliente2.setBorderPainted(false);
        btnCliente2.setContentAreaFilled(false);
        btnCliente2.setFocusable(false);
        btnCliente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCliente2ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel8.setText("Usuarios");

        btnCliente3.setBackground(new java.awt.Color(255, 255, 255));
        btnCliente3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/editar usuario.png"))); // NOI18N
        btnCliente3.setToolTipText("Editar usuario");
        btnCliente3.setBorder(null);
        btnCliente3.setBorderPainted(false);
        btnCliente3.setContentAreaFilled(false);
        btnCliente3.setFocusable(false);
        btnCliente3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCliente3ActionPerformed(evt);
            }
        });

        btnCliente4.setBackground(new java.awt.Color(255, 255, 255));
        btnCliente4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Ver.png"))); // NOI18N
        btnCliente4.setToolTipText("Consultar usuarios");
        btnCliente4.setBorder(null);
        btnCliente4.setBorderPainted(false);
        btnCliente4.setContentAreaFilled(false);
        btnCliente4.setFocusable(false);
        btnCliente4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCliente4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel8)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCliente2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCliente4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCliente3)))
                .addGap(0, 57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel8)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCliente2)
                    .addComponent(btnCliente3)
                    .addComponent(btnCliente4))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCliente1ActionPerformed
        NuevoCliente p = new NuevoCliente();
        p.setVisible(true);
    }//GEN-LAST:event_btnCliente1ActionPerformed

    private void btnCliente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCliente2ActionPerformed
        NuevoUsuario p = new NuevoUsuario();
        p.setVisible(true);
    }//GEN-LAST:event_btnCliente2ActionPerformed

    private void btnCliente3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCliente3ActionPerformed
        EditarUsuario p = new EditarUsuario();
        p.setVisible(true);
    }//GEN-LAST:event_btnCliente3ActionPerformed

    private void btnCliente4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCliente4ActionPerformed
       
        MostrarUsuarios p;
        try {
            p = new MostrarUsuarios();
            p.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(MenuAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_btnCliente4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCliente1;
    private javax.swing.JButton btnCliente2;
    private javax.swing.JButton btnCliente3;
    private javax.swing.JButton btnCliente4;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
